==== Overview
The eu.dariolucia.reatmetric.persist.timescale module is the basic implementation of a storage system for ReatMetric data such
as parameters, events, activity occurrences, raw data and operational messages, based on the PostgreSQL RDBMS with the
timescaledb extension.

Including this module in a ReatMetric system is not mandatory: if not present, the system will work as usual, but it will
not store any data. In the same way, it will not be possible to retrieve any historical data, but only monitor the live
state of the external devices/systems.

This module can be deployed outside a ReatMetric system, if a means to access the stored data outside the ReatMetric
system is desirable, keeping in mind that archives in a client-server deployment can be accessed in parallel by more than
a single system. If this module wants to be used for this purpose, the constructor argument string of the Archive class
must take a JDBC connection string (see configuration).

This module has one internal dependency:

* On eu.dariolucia.reatmetric.api

This module has one external dependency:

* On PostgreSQL JDBC connector.

==== Configuration
The *archive-location* element in the ReatMetric Core configuration file shall be set to a string with the following
format:

----
jdbc:postgresql://<ip>:<port>/<database name>?user=<username>&password=<password>
----

This archive implementation does not create the database automatically: the database must be created in advance and the
right priviledges must be assigned to the user configured in the ReatMetric system.
The following instructions can be performed as user 'postgres' for this purpose, or with any user that has the right to
create databases, to manage users and roles, and to activate extensions on PostgreSQL. If you use another user,
make sure that you change it also in the 4th command below.

----
CREATE DATABASE reatmetric_db;
CREATE USER reatmetric_user WITH ENCRYPTED PASSWORD 'reatmetric_password';
GRANT ALL PRIVILEGES ON DATABASE reatmetric_db TO reatmetric_user;
\c reatmetric_db postgres
GRANT ALL ON SCHEMA public TO reatmetric_user;
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
----