==== Overview
The eu.dariolucia.reatmetric.remoting module provides an application to publish a IReatmetricSystem implementation on a
RMI registry, in order to make it accessible via Java RMI to the ReatMetric UI application and to other external
applications via Java RMI. In this way, a ReatMetric system can run as a back-end application, regardless of the
presence of a connected user interface.

The application requires one mandatory parameter and one optional parameter:

* The first, mandatory, parameter indicates the TCP/IP port, the application will use to register the RMI Naming Service;
* The second, optional, parameter specifies the name of the ReatMetric system that must be registered to the RMI Naming
Service. If no name is provided, then the application registers all ReatMetric systems that are found.

This module looks up an implementation of the IReatmetricRegistry using the Java ServiceLoader. This means that, if this
application needs to be used in conjunction with the eu.dariolucia.reatmetric.core implementation, all the prerequisites
in terms of system variable and configurations of such module must be respected. The module then registers the
IReatmetricSystem instance using the system name of the instance.

This module has one internal dependency:

* On eu.dariolucia.reatmetric.api

This module has no external dependencies.

==== Configuration
It is possible to configure the TCP port to be used by RMI-exported objects by setting the system property:

----
-Dreatmetric.remoting.rmi.export.port=<port number>
----

If the system property is not specified, this value is set to 0 by default, implying that a random port will be selected
and announced to the remote RMI clients. If the remoting system is running behing a firewall, this behaviour would prevent
remote clients to connect to the exported objects.

RMI-exported objects will announce their reachability for responses and in case of callbacks, using an IP address that it
is taken by the Java RMI implementation using one of those available on the machine besides localhost. If it is needed
to force the selection of the IP address that is communicated to the remote objects, the following system property
shall be used. On the server side (i.e. ReatMetric system backend) this is rarely needed. One situation that requires this
configuration is when the ReatMetric instance runs inside a Docker container and the IP to be announced is the one of
the host machine and not the one of the container.

----
java -Djava.rmi.server.hostname=<server IP to use for local connections>
----
