This part of the documentation provides a step-by-step guide on how to create, implement and deploy a new ReatMetric
driver from scratch. This guide will assume adequate knowledge of Java and Maven.

The example driver presented here is very simple:

- it implements a connector, that can be started and stopped.
- When the connector is started, the driver publishes a single parameter value every second to the ReatMetric processing model, increasing its value by one;
- it raises one event when the counter is a multiple of 10;
- it handles an activity that resets the counter to 0.

==== Step 1: Create a new Maven project

Create an empty folder and put inside this folder the pom file and the necessary Maven folders. As a minimum, the folder
src/main/java needs to exist. The pom file must contain as a minimum the dependencies to the API and Core modules.

[source, xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>eu.dariolucia.reatmetric.example</groupId>
    <artifactId>eu.dariolucia.reatmetric.driver.example</artifactId>
    <name>REATMETRIC DRIVER - Example driver</name>
    <version>1.1.0</version>
    <description>REATMETRIC driver module for documentation purposes</description>
    <packaging>jar</packaging>

    <properties>
        <!-- Encoding -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <build>
        <plugins>
            <!-- Maven version to use -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.5</version>
                <configuration>
                    <generateBackupPoms>false</generateBackupPoms>
                </configuration>
            </plugin>
            <!-- Set the source file version to Java 11-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>eu.dariolucia.reatmetric</groupId>
            <artifactId>eu.dariolucia.reatmetric.api</artifactId>
            <version>1.1.0</version>
        </dependency>
		<dependency>
            <groupId>eu.dariolucia.reatmetric</groupId>
            <artifactId>eu.dariolucia.reatmetric.core</artifactId>
            <version>1.1.0</version>
        </dependency>
		<dependency>
            <groupId>eu.dariolucia.reatmetric</groupId>
            <artifactId>eu.dariolucia.reatmetric.processing</artifactId>
            <version>1.1.0</version>
        </dependency>
    </dependencies>
</project>
----

By running:

    mvn clean install

the project should build without errors.

==== Step 2: Create the driver module file and the class entrypoint

Create the file module-info.java with the information about the module dependencies. As a minimum, the following dependencies
shall be listed.

[source, java]
----
open module eu.dariolucia.reatmetric.driver.example {
    requires java.rmi;
    requires eu.dariolucia.reatmetric.api;
    requires eu.dariolucia.reatmetric.core;
}
----

Create a class named ExampleDriver inside package eu.dariolucia.reatmetric.driver.example, extending from AbstractDriver,
as shown below (imports are omitted).

[source,java]
----
public class ExampleDriver extends AbstractDriver {

    public List<DebugInformation> currentDebugInfo() {
        return Collections.emptyList();
    }

    protected SystemStatus startProcessing() throws DriverException {
        return SystemStatus.NOMINAL;
    }

    protected SystemStatus processConfiguration(String driverConfiguration, ServiceCoreConfiguration coreConfiguration, IServiceCoreContext context) throws DriverException {
        return SystemStatus.NOMINAL;
    }
}
----

Update the module-info.java to export the driver implementation as Java service.

[source, java]
----
open module eu.dariolucia.reatmetric.driver.example {
    requires java.rmi;
    requires eu.dariolucia.reatmetric.api;
    requires eu.dariolucia.reatmetric.core;
    exports eu.dariolucia.reatmetric.driver.example;
    provides eu.dariolucia.reatmetric.core.api.IDriver with eu.dariolucia.reatmetric.driver.example.ExampleDriver;
}
----

==== Step 3: Initialise the driver from the configuration

The driver needs to know which are the IDs of the related parameter and event objects in the processing model, as well
as to know the ID of the supported activity. The approach used for this example is very simple: the configuration string
is the path of the parent system element and the child system elements are expected to be present there. The IDs of such
element are then retrieved during the starting phase.

[source, java]
----
public class ExampleDriver extends AbstractDriver {

    private final String PARAMETER_NAME = "Example-Parameter";
    private final String EVENT_NAME = "Example-Event";
    private final String ACTIVITY_NAME = "Example-Activity";

    private SystemEntityPath parentSystemElement;

    private int parameterId;
    private int eventId;
    private int activityId;

    public List<DebugInformation> currentDebugInfo() {
        return Collections.emptyList();
    }

    protected SystemStatus startProcessing() throws DriverException {
        // Resolve the paths into IDs
        try {
            this.parameterId = getContext().getProcessingModel().getDescriptorOf(this.parentSystemElement.append(PARAMETER_NAME)).getExternalId();
            this.eventId = getContext().getProcessingModel().getDescriptorOf(this.parentSystemElement.append(PARAMETER_NAME)).getExternalId();
            this.activityId = getContext().getProcessingModel().getDescriptorOf(this.parentSystemElement.append(PARAMETER_NAME)).getExternalId();
        } catch (ReatmetricException e) {
            throw new DriverException(e);
        }
        return SystemStatus.NOMINAL;
    }

    protected SystemStatus processConfiguration(String driverConfiguration, ServiceCoreConfiguration coreConfiguration, IServiceCoreContext context) throws DriverException {
        this.parentSystemElement = SystemEntityPath.fromString(driverConfiguration);
        return SystemStatus.NOMINAL;
    }
}
----

==== Step 4: Add a connector, implement data injection in the processing model

Create a class in the package eu.dariolucia.reatmetric.driver.example, named ExampleConnector and extending from the
AbstractConnector class, as shown below. This class is used to control the start and stop of the parameter publication.

[source, java]
----
public class ExampleConnector extends AbstractTransportConnector {

    private final ExampleDriver driver;
    private Thread countingThread;
    private volatile boolean started = false;
    private final AtomicLong counter = new AtomicLong(0);

    public ExampleConnector(String name, String description, ExampleDriver driver) {
        super(name, description);
        this.driver = driver;
    }

    @Override
    protected Pair<Long, Long> computeBitrate() {
        return null; // No TX,RX data rate computed
    }

    @Override
    protected synchronized void doConnect() throws TransportException {
        // If the counting thread is not started, start the thread
        if(this.countingThread == null) {
            updateAlarmState(AlarmState.NOT_APPLICABLE);
            updateConnectionStatus(TransportConnectionStatus.CONNECTING);
            this.started = true;
            this.countingThread = new Thread(this::countingLoop);
            this.countingThread.setDaemon(true);
            this.countingThread.start();
        }
    }

    private void countingLoop() {
        updateConnectionStatus(TransportConnectionStatus.OPEN);
        while(started) {
            long toDistribute = this.counter.getAndIncrement();
            this.driver.newValue(toDistribute);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                // No action needed here
            }
        }
        updateConnectionStatus(TransportConnectionStatus.IDLE);
    }

    @Override
    protected synchronized void doDisconnect() throws TransportException {
        // If the counting thread is started, stop the thread
        if(this.countingThread != null) {
            updateConnectionStatus(TransportConnectionStatus.DISCONNECTING);
            this.started = false;
            this.countingThread.interrupt();
            try {
                this.countingThread.join();
            } catch (InterruptedException e) {
                // Nothing to be done here
            }
            this.countingThread = null;
        }
    }

    @Override
    protected void doDispose() {
        // Nothing to be done here
    }

    @Override
    public void abort() throws TransportException, RemoteException {
        disconnect();
    }
}
----

The ExampleDriver class must now be extended to:

- Create the connector in the starting phase;
- Return the connector as supported connector;
- Implement the newValue(long) method.

[source, java]
----
public class ExampleDriver extends AbstractDriver {

    private final String PARAMETER_NAME = "Example-Parameter";
    private final String EVENT_NAME = "Example-Event";
    private final String ACTIVITY_NAME = "Example-Activity";

    private SystemEntityPath parentSystemElement;

    private int parameterId;
    private int eventId;
    private int activityId;

    private ExampleConnector connector;

    public List<DebugInformation> currentDebugInfo() {
        return Collections.emptyList();
    }

    protected SystemStatus startProcessing() throws DriverException {
        // Resolve the paths into IDs
        try {
            this.parameterId = getContext().getProcessingModel().getDescriptorOf(this.parentSystemElement.append(PARAMETER_NAME)).getExternalId();
            this.eventId = getContext().getProcessingModel().getDescriptorOf(this.parentSystemElement.append(PARAMETER_NAME)).getExternalId();
            this.activityId = getContext().getProcessingModel().getDescriptorOf(this.parentSystemElement.append(PARAMETER_NAME)).getExternalId();
        } catch (ReatmetricException e) {
            throw new DriverException(e);
        }
        // Create the connector
        this.connector = new ExampleConnector("Example Connector", "Example Connector Description", this);
        // The connector prepare() must be called before being able to use it
        this.connector.prepare();
        // If we are here, all fine
        return SystemStatus.NOMINAL;
    }

    protected SystemStatus processConfiguration(String driverConfiguration, ServiceCoreConfiguration coreConfiguration, IServiceCoreContext context) throws DriverException {
        this.parentSystemElement = SystemEntityPath.fromString(driverConfiguration);
        return SystemStatus.NOMINAL;
    }

    @Override
    public List<ITransportConnector> getTransportConnectors() {
        return Collections.singletonList(this.connector);
    }

    public void newValue(long toDistribute) {
        // Parameter injection
        ParameterSample sample = ParameterSample.of(this.parameterId, toDistribute);
        getContext().getProcessingModel().injectParameters(Collections.singletonList(sample));
        // Event injection
        if(toDistribute % 10 == 0) {
            EventOccurrence event = EventOccurrence.of(this.eventId);
            getContext().getProcessingModel().raiseEvent(event);
        }
    }
}
----

==== Step 5: Add an activity handler

Create a class in the package eu.dariolucia.reatmetric.driver.example, named ExampleHandler and implementing the
IActivityHandler interface, as shown below. This class is used to manage the requests of activity executions.

[source, java]
----
public class ExampleHandler implements IActivityHandler {

    private final ExampleDriver driver;

    public ExampleHandler(ExampleDriver driver) {
        this.driver = driver;
    }

    @Override
    public void registerModel(IProcessingModel model) {
        // Not needed
    }

    @Override
    public void deregisterModel(IProcessingModel model) {
        // Not needed
    }

    @Override
    public List<String> getSupportedRoutes() {
        return Collections.singletonList(ExampleDriver.ROUTE_NAME);
    }

    @Override
    public List<String> getSupportedActivityTypes() {
        return Collections.singletonList(ExampleDriver.ACTIVITY_TYPE);
    }

    @Override
    public void executeActivity(ActivityInvocation activityInvocation) throws ActivityHandlingException {
        // Check if the connector is active
        if(!driver.isConnectorStarted()) {
            throw new ActivityHandlingException("Connector not started");
        }
        // Check if the route is OK
        if(!activityInvocation.getRoute().equals(ExampleDriver.ROUTE_NAME)) {
            throw new ActivityHandlingException("Route mismatch");
        }
        // Check if the activity is the one you expect (ID and path are matching)
        if(!driver.isActivitySupported(activityInvocation.getPath(), activityInvocation.getActivityId())) {
            throw new ActivityHandlingException("ID/Path mismatch");
        }
        // If so, inform that the RELEASE is done and invoke the request asynchronously to the connector
        // (a service executor would help, but this is an example)
        new Thread(() -> {
            driver.executeCounterReset(activityInvocation);
        }).start();
    }

    @Override
    public boolean getRouteAvailability(String route) throws ActivityHandlingException {
        return route.equals(ExampleDriver.ROUTE_NAME) && driver.isConnectorStarted();
    }

    @Override
    public void abortActivity(int activityId, IUniqueId activityOccurrenceId) throws ActivityHandlingException {
        // Not supported for this driver
        throw new ActivityHandlingException("Operation not supported");
    }
}
----

The ExampleDriver class must now be extended to:

- Create the activity handler in the starting phase;
- Return the activity handler as supported connector;
- Implement the necessary methods to implement the activity occurrence lifecycle.

[source, java]
----
public class ExampleDriver extends AbstractDriver {

    public static final String ROUTE_NAME = "Example Route";
    public static final String ACTIVITY_TYPE = "Example Activity Type";
    public static final String RESET_EXECUTION_NAME = "Reset Execution";
    private final String PARAMETER_NAME = "Example-Parameter";
    private final String EVENT_NAME = "Example-Event";
    private final String ACTIVITY_NAME = "Example-Activity";

    private SystemEntityPath parentSystemElement;

    private int parameterId;
    private int eventId;
    private int activityId;

    private ExampleConnector connector;
    private ExampleHandler handler;

    public List<DebugInformation> currentDebugInfo() {
        return Collections.emptyList();
    }

    protected SystemStatus startProcessing() throws DriverException {
        // Resolve the paths into IDs
        try {
            this.parameterId = getContext().getProcessingModel().getDescriptorOf(this.parentSystemElement.append(PARAMETER_NAME)).getExternalId();
            this.eventId = getContext().getProcessingModel().getDescriptorOf(this.parentSystemElement.append(EVENT_NAME)).getExternalId();
            this.activityId = getContext().getProcessingModel().getDescriptorOf(this.parentSystemElement.append(ACTIVITY_NAME)).getExternalId();
        } catch (ReatmetricException e) {
            throw new DriverException(e);
        }
        // Create the connector
        this.connector = new ExampleConnector("Example Connector", "Example Connector Description", this);
        // The connector prepare() must be called before being able to use it
        this.connector.prepare();
        // Create the activity handler
        this.handler = new ExampleHandler(this);
        // If we are here, all fine
        return SystemStatus.NOMINAL;
    }

    protected SystemStatus processConfiguration(String driverConfiguration, ServiceCoreConfiguration coreConfiguration, IServiceCoreContext context) throws DriverException {
        this.parentSystemElement = SystemEntityPath.fromString(driverConfiguration);
        return SystemStatus.NOMINAL;
    }

    @Override
    public List<IActivityHandler> getActivityHandlers() {
        return Collections.singletonList(this.handler);
    }

    @Override
    public List<ITransportConnector> getTransportConnectors() {
        return Collections.singletonList(this.connector);
    }

    public void newValue(long toDistribute) {
        // Parameter injection
        ParameterSample sample = ParameterSample.of(this.parameterId, toDistribute);
        getContext().getProcessingModel().injectParameters(Collections.singletonList(sample));
        // Event injection
        if(toDistribute % 10 == 0) {
            EventOccurrence event = EventOccurrence.of(this.eventId);
            getContext().getProcessingModel().raiseEvent(event);
        }
    }

    public boolean isConnectorStarted() {
        return this.connector.getConnectionStatus() == TransportConnectionStatus.OPEN;
    }

    public boolean isActivitySupported(SystemEntityPath path, int requestedActivity) {
        return path.equals(this.parentSystemElement.append(ACTIVITY_NAME)) && requestedActivity == this.activityId;
    }

    public void executeCounterReset(IActivityHandler.ActivityInvocation activityInvocation) {
        // Informing that we are proceeding with the release of the activity occurrence, and that, if it works, we go
        // directly in the EXECUTION state
        reportActivityState(activityInvocation.getActivityId(), activityInvocation.getActivityOccurrenceId(), Instant.now(),
                ActivityOccurrenceState.RELEASE, ActivityOccurrenceReport.RELEASE_REPORT_NAME, ActivityReportState.PENDING,
                ActivityOccurrenceState.EXECUTION);
        if(!isConnectorStarted()) {
            // Connector not started, release failed
            reportActivityState(activityInvocation.getActivityId(), activityInvocation.getActivityOccurrenceId(), Instant.now(),
                    ActivityOccurrenceState.RELEASE, ActivityOccurrenceReport.RELEASE_REPORT_NAME, ActivityReportState.FATAL,
                    ActivityOccurrenceState.RELEASE);
            // That's it
            return;
        } else {
            // Connector started, release OK, pending execution
            reportActivityState(activityInvocation.getActivityId(), activityInvocation.getActivityOccurrenceId(), Instant.now(),
                    ActivityOccurrenceState.RELEASE, ActivityOccurrenceReport.RELEASE_REPORT_NAME, ActivityReportState.OK,
                    ActivityOccurrenceState.EXECUTION);
            reportActivityState(activityInvocation.getActivityId(), activityInvocation.getActivityOccurrenceId(), Instant.now(),
                    ActivityOccurrenceState.EXECUTION, RESET_EXECUTION_NAME, ActivityReportState.PENDING,
                    ActivityOccurrenceState.VERIFICATION);
        }
        // Execution of the activity
        boolean resetCounter = this.connector.resetCounter();
        if(resetCounter) {
            // Good, activity finished OK
            reportActivityState(activityInvocation.getActivityId(), activityInvocation.getActivityOccurrenceId(), Instant.now(),
                    ActivityOccurrenceState.EXECUTION, RESET_EXECUTION_NAME, ActivityReportState.OK,
                    ActivityOccurrenceState.VERIFICATION);
        } else {
            // Bad, activity finished with error
            reportActivityState(activityInvocation.getActivityId(), activityInvocation.getActivityOccurrenceId(), Instant.now(),
                    ActivityOccurrenceState.EXECUTION, RESET_EXECUTION_NAME, ActivityReportState.FATAL,
                    ActivityOccurrenceState.EXECUTION);
        }
    }
}
----

Finally, the ExampleConnector must be extended to implement the method resetCounter, which is trivial.

[source, java]
----
public class ExampleConnector extends AbstractTransportConnector {

    private final ExampleDriver driver;
    private Thread countingThread;
    private volatile boolean started = false;
    private final AtomicLong counter = new AtomicLong(0);

    public ExampleConnector(String name, String description, ExampleDriver driver) {
        super(name, description);
        this.driver = driver;
    }

    @Override
    protected Pair<Long, Long> computeBitrate() {
        return null; // No TX,RX data rate computed
    }

    @Override
    protected synchronized void doConnect() throws TransportException {
        // If the counting thread is not started, start the thread
        if(this.countingThread == null) {
            updateAlarmState(AlarmState.NOT_APPLICABLE);
            updateConnectionStatus(TransportConnectionStatus.CONNECTING);
            this.started = true;
            this.countingThread = new Thread(this::countingLoop);
            this.countingThread.setDaemon(true);
            this.countingThread.start();
        }
    }

    private void countingLoop() {
        updateConnectionStatus(TransportConnectionStatus.OPEN);
        while(started) {
            long toDistribute = this.counter.getAndIncrement();
            this.driver.newValue(toDistribute);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                // No action needed here
            }
        }
        updateConnectionStatus(TransportConnectionStatus.IDLE);
    }

    @Override
    protected synchronized void doDisconnect() throws TransportException {
        // If the counting thread is started, stop the thread
        if(this.countingThread != null) {
            updateConnectionStatus(TransportConnectionStatus.DISCONNECTING);
            this.started = false;
            this.countingThread.interrupt();
            try {
                this.countingThread.join();
            } catch (InterruptedException e) {
                // Nothing to be done here
            }
            this.countingThread = null;
        }
    }

    @Override
    protected void doDispose() {
        // Nothing to be done here
    }

    @Override
    public void abort() throws TransportException, RemoteException {
        disconnect();
    }

    public boolean resetCounter() {
        if(getConnectionStatus() != TransportConnectionStatus.OPEN) {
            return false;
        }
        this.counter.set(0);
        return true;
    }
}
----

==== Step 6: Prepare the processing model definition

Create an XML file with the following content:

[source, xml]
----
<ns1:processing xmlns:ns1="http://dariolucia.eu/reatmetric/processing/definition">
    <parameters>
		<!-- Counter -->
		<parameter id="#100" location="EXAMPLE.SYSTEM.DRIVER.Example-Parameter"
                   description="Example parameter - counter"
                   raw_type="SIGNED_INTEGER" eng_type="SIGNED_INTEGER" eng_unit="" />
    </parameters>
    <events>
        <!-- Event for % 10 condition -->
        <event id="#101" location="EXAMPLE.SYSTEM.DRIVER.Example-Event" description="Example event"
               severity="INFO" type="EXAMPLE_EVENT_TYPE"/>
    </events>
    <activities>
        <!-- Activity for counter reset -->
        <activity id="#102" location="EXAMPLE.SYSTEM.DRIVER.Example-Activity"
                  description="Example activity - reset counter" type="Example Activity Type"
                  verification_timeout="5" >
            <verification>
                <!-- Check that the value of the counter goes to 0 -->
                <expression>COUNTER == 0</expression>
                <symbol name="COUNTER" reference="#100" binding="ENG_VALUE" />
            </verification>
        </activity>
    </activities>
</ns1:processing>
----

It is possible to recognise the three system entities (parameter, event and activity), plus a special post-execution
verification for the activity, which confirms the reset using the value provided by the parameter.

The driver is completed. The next section explains how to create a new ReatMetric deployment, and to configure it to
use this driver.

The full driver source code can be found in the module eu.dariolucia.reatmetric.driver.example.
